version: '3'

services:
  tcpcustom:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tcpcustom
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8081:8081"
    volumes:
      - ./captures:/root/captures
    command: ["--host", "example.com", "--port", "80", "--fp", "windows", "--tun", "tun4", "--lport", "8082", "--capture", "/root/captures/traffic.pcap"]